export const MONSTER_SIZE_OPTIONS = [
  'Tiny',
  'Small',
  'Medium',
  'Large',
  'Huge',
  'Gargantuan',
];

export const MONSTER_RACE_OPTIONS = [
  'Aberration',
  'Beast',
  'Celestial',
  'Construct',
  'Dragon',
  'Elemental',
  'Fey',
  'Fiend',
  'Giant',
  'Humanoid',
  'Monstrosity',
  'Ooze',
  'Plant',
  'Undead',
];

export const MONSTER_ABILITY_OPTIONS = [
  'Strength',
  'Dexterity',
  'Constitution',
  'Intelligence',
  'Wisdom',
  'Charisma',
];

export const MONSTER_PROFICIENCY_OPTIONS = [
  'Strength Saving Throw',
  'Dexterity Saving Throw',
  'Constitution Saving Throw',
  'Intelligence Saving Throw',
  'Wisdom Saving Throw',
  'Charisma Saving Throw',
  'Acrobatics',
  'Animal Handling',
  'Arcana',
  'Athletics',
  'Deception',
  'History',
  'Insight',
  'Intimidation',
  'Investigation',
  'Medicine',
  'Nature',
  'Perception',
  'Performance',
  'Persuasion',
  'Religion',
  'Sleight of Hand',
  'Stealth',
  'Survival',
  'Simple Weapons',
  'Martial Weapons',
  'Light Armor',
  'Medium Armor',
  'Heavy Armor',
  'Shields',
];

export const MONSTER_SKILL_PROFICIENCY_OPTIONS = [
  'Acrobatics',
  'Animal Handling',
  'Arcana',
  'Athletics',
  'Deception',
  'History',
  'Insight',
  'Intimidation',
  'Investigation',
  'Medicine',
  'Nature',
  'Perception',
  'Performance',
  'Persuasion',
  'Religion',
  'Sleight of Hand',
  'Stealth',
  'Survival',
];
