// <auto-generated />
using LearningLab.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LearningLab.Data.Migrations
{
    [DbContext(typeof(LearningLabContext))]
    [Migration("20260721093000_CreateTable_CampaignNpcs_UpdateNpcProcedure")]
    partial class CreateTable_CampaignNpcs_UpdateNpcProcedure
    {
    }
}
