// <auto-generated />
using System;
using LearningLab.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearningLab.Data.Migrations
{
    [DbContext(typeof(LearningLabContext))]
    [Migration("20260710100915_Create_RBAC_Models")]
    partial class Create_RBAC_Models
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LearningLab.Data.Models.AccessControl.Permission", b =>
                {
                    b.Property<Guid>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("permission_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("name");

                    b.HasKey("PermissionId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("LearningLab.Data.Models.AccessControl.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("name");

                    b.HasKey("RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("LearningLab.Data.Models.AccessControl.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("LearningLab.Data.Models.AccessControl.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("LearningLab.Data.Models.Character.CharacterSheet", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<string>("Background")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("background");

                    b.Property<string>("CharacterClass")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("character_class");

                    b.PrimitiveCollection<string>("Equipment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("equipment");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_name");

                    b.Property<int?>("Height")
                        .HasColumnType("int")
                        .HasColumnName("height");

                    b.Property<string>("Information")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("information");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_name");

                    b.Property<int>("LogicRating")
                        .HasColumnType("int")
                        .HasColumnName("logic_rating");

                    b.Property<int>("MotoricsRating")
                        .HasColumnType("int")
                        .HasColumnName("motorics_rating");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nationality");

                    b.Property<int>("PhysicalRating")
                        .HasColumnType("int")
                        .HasColumnName("physical_rating");

                    b.Property<string>("PortraitUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("portrait_url");

                    b.Property<int>("PsycheRating")
                        .HasColumnType("int")
                        .HasColumnName("psyche_rating");

                    b.PrimitiveCollection<string>("Traits")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("traits");

                    b.Property<int?>("Weight")
                        .HasColumnType("int")
                        .HasColumnName("weight");

                    b.HasKey("UserId");

                    b.ToTable("CharacterSheets", null, t =>
                        {
                            t.HasCheckConstraint("CK_CharacterSheets_LogicRating", "[logic_rating] BETWEEN 0 AND 15");

                            t.HasCheckConstraint("CK_CharacterSheets_MotoricsRating", "[motorics_rating] BETWEEN 0 AND 15");

                            t.HasCheckConstraint("CK_CharacterSheets_PhysicalRating", "[physical_rating] BETWEEN 0 AND 15");

                            t.HasCheckConstraint("CK_CharacterSheets_PsycheRating", "[psyche_rating] BETWEEN 0 AND 15");
                        });
                });

            modelBuilder.Entity("LearningLab.Data.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_salt");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("LearningLab.Data.Models.AccessControl.RolePermission", b =>
                {
                    b.HasOne("LearningLab.Data.Models.AccessControl.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearningLab.Data.Models.AccessControl.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LearningLab.Data.Models.AccessControl.UserRole", b =>
                {
                    b.HasOne("LearningLab.Data.Models.AccessControl.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearningLab.Data.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearningLab.Data.Models.Character.CharacterSheet", b =>
                {
                    b.HasOne("LearningLab.Data.Models.User", "User")
                        .WithOne("CharacterSheet")
                        .HasForeignKey("LearningLab.Data.Models.Character.CharacterSheet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("LearningLab.Data.Models.Character.Action", "Actions", b1 =>
                        {
                            b1.Property<Guid>("CharacterSheetUserId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("ActionType")
                                .IsRequired();

                            b1.Property<string>("Description");

                            b1.Property<string>("Title");

                            b1.HasKey("CharacterSheetUserId", "__synthesizedOrdinal");

                            b1.ToTable("CharacterSheets");

                            b1
                                .ToJson("actions")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("CharacterSheetUserId");
                        });

                    b.Navigation("Actions");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearningLab.Data.Models.AccessControl.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("LearningLab.Data.Models.AccessControl.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("LearningLab.Data.Models.User", b =>
                {
                    b.Navigation("CharacterSheet");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
