// <auto-generated />
using System;
using LearningLab.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearningLab.Data.Migrations
{
    [DbContext(typeof(LearningLabContext))]
    [Migration("20260721081249_AlterTable_PlayerCampaignParticipation_IntroduceSkillValues")]
    partial class AlterTable_PlayerCampaignParticipation_IntroduceSkillValues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LearningLab.Data.Models.AccessControl.Permission", b =>
                {
                    b.Property<Guid>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("permission_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("name");

                    b.HasKey("PermissionId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("LearningLab.Data.Models.AccessControl.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("name");

                    b.HasKey("RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("LearningLab.Data.Models.AccessControl.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("LearningLab.Data.Models.AccessControl.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("LearningLab.Data.Models.Assets.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("asset_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("asset_type");

                    b.PrimitiveCollection<string>("CampaignIds")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("campaign_ids");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<string>("ItemType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("item_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentAssetId")
                        .HasColumnType("int")
                        .HasColumnName("parent_asset_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')");

                    b.HasKey("Id");

                    b.HasIndex("ParentAssetId", "Name")
                        .IsUnique()
                        .HasFilter("[parent_asset_id] IS NOT NULL");

                    b.ToTable("Assets", (string)null);
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.Campaign", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("campaign_id");

                    b.Property<string>("CampaignName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("campaign_name");

                    b.Property<string>("CampaignPictureUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("campaign_picture_url");

                    b.Property<DateTimeOffset>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')");

                    b.Property<Guid>("GameMasterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("game_master_id");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("version");

                    b.HasKey("CampaignId");

                    b.HasIndex("GameMasterId");

                    b.ToTable("Campaigns", (string)null);
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.CampaignMilestone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("campaign_milestone_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("AchievedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("achieved_at");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("description");

                    b.Property<string>("Importance")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("importance");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "Title");

                    b.ToTable("CampaignMilestones", (string)null);
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.CampaignParticipationInvite", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("campaign_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("DateInvited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("date_invited")
                        .HasDefaultValueSql("TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')");

                    b.HasKey("CampaignId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("CampaignParticipationInvite", (string)null);
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.CampaignSettings", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("campaign_id");

                    b.Property<string>("CampaignDescription")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16384)
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("")
                        .HasColumnName("campaign_description");

                    b.Property<int>("MaxNumberOfPlayers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("max_number_of_players");

                    b.Property<string>("PassiveSkillsCheck")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasDefaultValue("Manual")
                        .HasColumnName("passive_skills_check");

                    b.HasKey("CampaignId");

                    b.ToTable("CampaignSettings", (string)null);
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.PlayerCampaignParticipation", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("campaign_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("DateJoined")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("date_joined")
                        .HasDefaultValueSql("TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')");

                    b.PrimitiveCollection<string>("ExpertiseSkills")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("expertise_skills");

                    b.PrimitiveCollection<string>("HalfProficientSkills")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("half_proficient_skills");

                    b.Property<string>("Nickname")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("nickname");

                    b.PrimitiveCollection<string>("ProficientSkills")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("proficient_skills");

                    b.HasKey("CampaignId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("PlayerCampaignParticipation", (string)null);
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.Quests.CampaignQuest", b =>
                {
                    b.Property<Guid>("QuestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("quest_id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<string>("GivenBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasDefaultValue("")
                        .HasColumnName("given_by");

                    b.Property<string>("Reward")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasDefaultValue("")
                        .HasColumnName("reward");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("quest_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')");

                    b.HasKey("QuestId");

                    b.HasIndex("CampaignId", "Title");

                    b.HasIndex("CampaignId", "Type", "CompletedAt");

                    b.ToTable("CampaignQuests", (string)null);
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.Quests.CampaignQuestTask", b =>
                {
                    b.Property<Guid>("QuestTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("quest_task_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')");

                    b.Property<DateTimeOffset?>("DateCompleted")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("date_completed");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("quest_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')");

                    b.HasKey("QuestTaskId");

                    b.HasIndex("QuestId", "DateCompleted");

                    b.HasIndex("QuestId", "Title");

                    b.ToTable("CampaignQuestTasks", (string)null);
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.Sessions.CampaignSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("SessionDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("session_date");

                    b.Property<int>("SessionNumber")
                        .HasColumnType("int")
                        .HasColumnName("session_number");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "SessionNumber")
                        .IsUnique();

                    b.ToTable("CampaignSessions", (string)null);
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.Sessions.SessionNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("session_note_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("note_order");

                    b.Property<int>("SessionId")
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("note_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Order")
                        .IsUnique();

                    b.ToTable("SessionNotes", (string)null);
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.Sessions.SessionNoteChoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("session_note_choice_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChoiceText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("choice_text");

                    b.Property<bool>("IsChosen")
                        .HasColumnType("bit")
                        .HasColumnName("is_chosen");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("choice_order");

                    b.Property<int>("SessionNoteId")
                        .HasColumnType("int")
                        .HasColumnName("session_note_id");

                    b.HasKey("Id");

                    b.HasIndex("SessionNoteId", "Order")
                        .IsUnique();

                    b.ToTable("SessionNoteChoices", (string)null);
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.Sessions.SessionNoteMechanicsChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("session_note_mechanics_change_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("change_text");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("change_order");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("player_id");

                    b.Property<int>("SessionNoteId")
                        .HasColumnType("int")
                        .HasColumnName("session_note_id");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SessionNoteId", "Order")
                        .IsUnique();

                    b.HasIndex("SessionNoteId", "PlayerId")
                        .IsUnique();

                    b.ToTable("SessionNoteMechanicsChanges", (string)null);
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.Story.StoryBeat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("story_beat_id");

                    b.Property<int?>("CampaignMilestoneId")
                        .HasColumnType("int")
                        .HasColumnName("campaign_milestone_id");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("order_index");

                    b.Property<string>("StoryBeatType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("story_beat_type");

                    b.Property<Guid>("StoryBlockId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("story_block_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasDefaultValue("")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("CampaignMilestoneId")
                        .IsUnique()
                        .HasFilter("[campaign_milestone_id] IS NOT NULL");

                    b.HasIndex("StoryBlockId");

                    b.HasIndex("StoryBlockId", "OrderIndex")
                        .IsUnique();

                    b.ToTable("StoryBeats", (string)null);
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.Story.StoryBlock", b =>
                {
                    b.Property<Guid>("StoryBlockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("story_block_id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("campaign_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasDefaultValue("")
                        .HasColumnName("title");

                    b.HasKey("StoryBlockId");

                    b.HasIndex("CampaignId");

                    b.ToTable("StoryBlocks", (string)null);
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.Story.StoryBlockMilestone", b =>
                {
                    b.Property<Guid>("StoryBlockId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("story_block_id");

                    b.Property<int>("CampaignMilestoneId")
                        .HasColumnType("int")
                        .HasColumnName("campaign_milestone_id");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("order_index");

                    b.HasKey("StoryBlockId", "CampaignMilestoneId");

                    b.HasIndex("CampaignMilestoneId")
                        .IsUnique();

                    b.HasIndex("StoryBlockId", "OrderIndex")
                        .IsUnique();

                    b.ToTable("StoryBlockMilestones", (string)null);
                });

            modelBuilder.Entity("LearningLab.Data.Models.Character.CharacterSheet", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<string>("Background")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("background");

                    b.Property<string>("CharacterClass")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("character_class");

                    b.PrimitiveCollection<string>("Equipment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("equipment");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_name");

                    b.Property<int?>("Height")
                        .HasColumnType("int")
                        .HasColumnName("height");

                    b.Property<string>("Information")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("information");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_name");

                    b.Property<int>("LogicRating")
                        .HasColumnType("int")
                        .HasColumnName("logic_rating");

                    b.Property<int>("MotoricsRating")
                        .HasColumnType("int")
                        .HasColumnName("motorics_rating");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nationality");

                    b.Property<int>("PhysicalRating")
                        .HasColumnType("int")
                        .HasColumnName("physical_rating");

                    b.Property<string>("PortraitUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("portrait_url");

                    b.Property<int>("PsycheRating")
                        .HasColumnType("int")
                        .HasColumnName("psyche_rating");

                    b.PrimitiveCollection<string>("Traits")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("traits");

                    b.Property<int?>("Weight")
                        .HasColumnType("int")
                        .HasColumnName("weight");

                    b.HasKey("UserId");

                    b.ToTable("CharacterSheets", null, t =>
                        {
                            t.HasCheckConstraint("CK_CharacterSheets_LogicRating", "[logic_rating] BETWEEN 0 AND 15");

                            t.HasCheckConstraint("CK_CharacterSheets_MotoricsRating", "[motorics_rating] BETWEEN 0 AND 15");

                            t.HasCheckConstraint("CK_CharacterSheets_PhysicalRating", "[physical_rating] BETWEEN 0 AND 15");

                            t.HasCheckConstraint("CK_CharacterSheets_PsycheRating", "[psyche_rating] BETWEEN 0 AND 15");
                        });
                });

            modelBuilder.Entity("LearningLab.Data.Models.Notifications.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("notification_id");

                    b.Property<DateTimeOffset>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("date_deleted");

                    b.Property<DateTimeOffset?>("DateRead")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("date_read");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("description");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("notification_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId", "DateDeleted", "DateCreated");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("LearningLab.Data.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_salt");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("LearningLab.Data.Models.AccessControl.RolePermission", b =>
                {
                    b.HasOne("LearningLab.Data.Models.AccessControl.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearningLab.Data.Models.AccessControl.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LearningLab.Data.Models.AccessControl.UserRole", b =>
                {
                    b.HasOne("LearningLab.Data.Models.AccessControl.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearningLab.Data.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearningLab.Data.Models.Assets.Asset", b =>
                {
                    b.HasOne("LearningLab.Data.Models.Assets.Asset", "ParentAsset")
                        .WithMany("Children")
                        .HasForeignKey("ParentAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentAsset");
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.Campaign", b =>
                {
                    b.HasOne("LearningLab.Data.Models.User", "GameMaster")
                        .WithMany("OwnedCampaigns")
                        .HasForeignKey("GameMasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameMaster");
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.CampaignMilestone", b =>
                {
                    b.HasOne("LearningLab.Data.Models.Campaign.Campaign", "Campaign")
                        .WithMany("Milestones")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.CampaignParticipationInvite", b =>
                {
                    b.HasOne("LearningLab.Data.Models.Campaign.Campaign", "Campaign")
                        .WithMany("ParticipationInvites")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearningLab.Data.Models.User", "User")
                        .WithMany("CampaignParticipationInvites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.CampaignSettings", b =>
                {
                    b.HasOne("LearningLab.Data.Models.Campaign.Campaign", "Campaign")
                        .WithOne("Settings")
                        .HasForeignKey("LearningLab.Data.Models.Campaign.CampaignSettings", "CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.PlayerCampaignParticipation", b =>
                {
                    b.HasOne("LearningLab.Data.Models.Campaign.Campaign", "Campaign")
                        .WithMany("PlayerParticipations")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearningLab.Data.Models.User", "User")
                        .WithMany("CampaignParticipations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("LearningLab.Data.Models.Campaign.PlayerCampaignParticipationAbilityValue", "AbilityValues", b1 =>
                        {
                            b1.Property<Guid>("PlayerCampaignParticipationCampaignId");

                            b1.Property<Guid>("PlayerCampaignParticipationUserId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Ability")
                                .IsRequired();

                            b1.Property<int>("Value");

                            b1.HasKey("PlayerCampaignParticipationCampaignId", "PlayerCampaignParticipationUserId", "__synthesizedOrdinal");

                            b1.ToTable("PlayerCampaignParticipation");

                            b1
                                .ToJson("ability_values")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("PlayerCampaignParticipationCampaignId", "PlayerCampaignParticipationUserId");
                        });

                    b.OwnsMany("LearningLab.Data.Models.Campaign.PlayerCampaignParticipationSkillValue", "SkillValues", b1 =>
                        {
                            b1.Property<Guid>("PlayerCampaignParticipationCampaignId");

                            b1.Property<Guid>("PlayerCampaignParticipationUserId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Skill")
                                .IsRequired();

                            b1.Property<int>("Value");

                            b1.HasKey("PlayerCampaignParticipationCampaignId", "PlayerCampaignParticipationUserId", "__synthesizedOrdinal");

                            b1.ToTable("PlayerCampaignParticipation");

                            b1
                                .ToJson("skill_values")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("PlayerCampaignParticipationCampaignId", "PlayerCampaignParticipationUserId");
                        });

                    b.Navigation("AbilityValues");

                    b.Navigation("Campaign");

                    b.Navigation("SkillValues");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.Quests.CampaignQuest", b =>
                {
                    b.HasOne("LearningLab.Data.Models.Campaign.Campaign", "Campaign")
                        .WithMany("Quests")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.Quests.CampaignQuestTask", b =>
                {
                    b.HasOne("LearningLab.Data.Models.Campaign.Quests.CampaignQuest", "CampaignQuest")
                        .WithMany("Tasks")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CampaignQuest");
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.Sessions.CampaignSession", b =>
                {
                    b.HasOne("LearningLab.Data.Models.Campaign.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.Sessions.SessionNote", b =>
                {
                    b.HasOne("LearningLab.Data.Models.Campaign.Sessions.CampaignSession", "Session")
                        .WithMany("Notes")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.Sessions.SessionNoteChoice", b =>
                {
                    b.HasOne("LearningLab.Data.Models.Campaign.Sessions.SessionNote", "SessionNote")
                        .WithMany("Choices")
                        .HasForeignKey("SessionNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionNote");
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.Sessions.SessionNoteMechanicsChange", b =>
                {
                    b.HasOne("LearningLab.Data.Models.User", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearningLab.Data.Models.Campaign.Sessions.SessionNote", "SessionNote")
                        .WithMany("MechanicsChanges")
                        .HasForeignKey("SessionNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("SessionNote");
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.Story.StoryBeat", b =>
                {
                    b.HasOne("LearningLab.Data.Models.Campaign.CampaignMilestone", "Milestone")
                        .WithOne("StoryBeat")
                        .HasForeignKey("LearningLab.Data.Models.Campaign.Story.StoryBeat", "CampaignMilestoneId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LearningLab.Data.Models.Campaign.Story.StoryBlock", "StoryBlock")
                        .WithMany("Beats")
                        .HasForeignKey("StoryBlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LearningLab.Data.Models.Campaign.Story.StoryBeatInformation", "Information", b1 =>
                        {
                            b1.Property<Guid>("StoryBeatId");

                            b1.Property<string>("Narrative")
                                .IsRequired();

                            b1.HasKey("StoryBeatId");

                            b1.ToTable("StoryBeats");

                            b1
                                .ToJson("information")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("StoryBeatId");

                            b1.OwnsMany("LearningLab.Data.Models.Campaign.Story.StoryBeatOptionalInformation", "OptionalInformation", b2 =>
                                {
                                    b2.Property<Guid>("StoryBeatInformationStoryBeatId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<int>("DifficultyClass");

                                    b2.Property<string>("Information")
                                        .IsRequired();

                                    b2.Property<int?>("NarrativeOffset");

                                    b2.Property<string>("Placement")
                                        .IsRequired();

                                    b2.Property<string>("Skill")
                                        .IsRequired();

                                    b2.HasKey("StoryBeatInformationStoryBeatId", "__synthesizedOrdinal");

                                    b2.ToTable("StoryBeats");

                                    b2.WithOwner()
                                        .HasForeignKey("StoryBeatInformationStoryBeatId");
                                });

                            b1.Navigation("OptionalInformation");
                        });

                    b.OwnsOne("LearningLab.Data.Models.Campaign.Story.StoryBeatNarrative", "Narrative", b1 =>
                        {
                            b1.Property<Guid>("StoryBeatId");

                            b1.HasKey("StoryBeatId");

                            b1.ToTable("StoryBeats");

                            b1
                                .ToJson("narrative")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("StoryBeatId");

                            b1.OwnsMany("LearningLab.Data.Models.Campaign.Story.StoryBeatNarrativeParagraph", "Paragraphs", b2 =>
                                {
                                    b2.Property<Guid>("StoryBeatNarrativeStoryBeatId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<int>("OrderIndex");

                                    b2.Property<string>("Text")
                                        .IsRequired();

                                    b2.HasKey("StoryBeatNarrativeStoryBeatId", "__synthesizedOrdinal");

                                    b2.ToTable("StoryBeats");

                                    b2.WithOwner()
                                        .HasForeignKey("StoryBeatNarrativeStoryBeatId");
                                });

                            b1.Navigation("Paragraphs");
                        });

                    b.OwnsOne("LearningLab.Data.Models.Campaign.Story.StoryBeatRoleplaying", "Roleplaying", b1 =>
                        {
                            b1.Property<Guid>("StoryBeatId");

                            b1.Property<string>("MainDescription")
                                .IsRequired();

                            b1.HasKey("StoryBeatId");

                            b1.ToTable("StoryBeats");

                            b1
                                .ToJson("roleplaying")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("StoryBeatId");

                            b1.OwnsMany("LearningLab.Data.Models.Campaign.Story.StoryBeatRoleplayingInformation", "DiscoverableInformation", b2 =>
                                {
                                    b2.Property<Guid>("StoryBeatRoleplayingStoryBeatId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<string>("Ability");

                                    b2.Property<string>("CheckType")
                                        .IsRequired();

                                    b2.Property<int?>("DifficultyClass");

                                    b2.Property<string>("Information")
                                        .IsRequired();

                                    b2.Property<string>("NpcName")
                                        .IsRequired();

                                    b2.Property<string>("Skill");

                                    b2.HasKey("StoryBeatRoleplayingStoryBeatId", "__synthesizedOrdinal");

                                    b2.ToTable("StoryBeats");

                                    b2.WithOwner()
                                        .HasForeignKey("StoryBeatRoleplayingStoryBeatId");
                                });

                            b1.OwnsMany("LearningLab.Data.Models.Campaign.Story.StoryBeatRoleplayingNpc", "Npcs", b2 =>
                                {
                                    b2.Property<Guid>("StoryBeatRoleplayingStoryBeatId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<string>("Description")
                                        .IsRequired();

                                    b2.Property<string>("Name")
                                        .IsRequired();

                                    b2.HasKey("StoryBeatRoleplayingStoryBeatId", "__synthesizedOrdinal");

                                    b2.ToTable("StoryBeats");

                                    b2.WithOwner()
                                        .HasForeignKey("StoryBeatRoleplayingStoryBeatId");
                                });

                            b1.Navigation("DiscoverableInformation");

                            b1.Navigation("Npcs");
                        });

                    b.Navigation("Information");

                    b.Navigation("Milestone");

                    b.Navigation("Narrative");

                    b.Navigation("Roleplaying");

                    b.Navigation("StoryBlock");
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.Story.StoryBlock", b =>
                {
                    b.HasOne("LearningLab.Data.Models.Campaign.Campaign", "Campaign")
                        .WithMany("StoryBlocks")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.Story.StoryBlockMilestone", b =>
                {
                    b.HasOne("LearningLab.Data.Models.Campaign.CampaignMilestone", "CampaignMilestone")
                        .WithMany("StoryBlockMilestones")
                        .HasForeignKey("CampaignMilestoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearningLab.Data.Models.Campaign.Story.StoryBlock", "StoryBlock")
                        .WithMany("Milestones")
                        .HasForeignKey("StoryBlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CampaignMilestone");

                    b.Navigation("StoryBlock");
                });

            modelBuilder.Entity("LearningLab.Data.Models.Character.CharacterSheet", b =>
                {
                    b.HasOne("LearningLab.Data.Models.User", "User")
                        .WithOne("CharacterSheet")
                        .HasForeignKey("LearningLab.Data.Models.Character.CharacterSheet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("LearningLab.Data.Models.Character.Action", "Actions", b1 =>
                        {
                            b1.Property<Guid>("CharacterSheetUserId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("ActionType")
                                .IsRequired();

                            b1.Property<string>("Description");

                            b1.Property<string>("Title");

                            b1.HasKey("CharacterSheetUserId", "__synthesizedOrdinal");

                            b1.ToTable("CharacterSheets");

                            b1
                                .ToJson("actions")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("CharacterSheetUserId");
                        });

                    b.Navigation("Actions");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearningLab.Data.Models.Notifications.Notification", b =>
                {
                    b.HasOne("LearningLab.Data.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearningLab.Data.Models.AccessControl.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("LearningLab.Data.Models.AccessControl.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("LearningLab.Data.Models.Assets.Asset", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.Campaign", b =>
                {
                    b.Navigation("Milestones");

                    b.Navigation("ParticipationInvites");

                    b.Navigation("PlayerParticipations");

                    b.Navigation("Quests");

                    b.Navigation("Settings")
                        .IsRequired();

                    b.Navigation("StoryBlocks");
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.CampaignMilestone", b =>
                {
                    b.Navigation("StoryBeat");

                    b.Navigation("StoryBlockMilestones");
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.Quests.CampaignQuest", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.Sessions.CampaignSession", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.Sessions.SessionNote", b =>
                {
                    b.Navigation("Choices");

                    b.Navigation("MechanicsChanges");
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.Story.StoryBlock", b =>
                {
                    b.Navigation("Beats");

                    b.Navigation("Milestones");
                });

            modelBuilder.Entity("LearningLab.Data.Models.User", b =>
                {
                    b.Navigation("CampaignParticipationInvites");

                    b.Navigation("CampaignParticipations");

                    b.Navigation("CharacterSheet");

                    b.Navigation("Notifications");

                    b.Navigation("OwnedCampaigns");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
