// <auto-generated />
using System;
using LearningLab.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearningLab.Data.Migrations
{
    [DbContext(typeof(LearningLabContext))]
    partial class LearningLabContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LearningLab.Data.Models.AccessControl.Permission", b =>
                {
                    b.Property<Guid>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("permission_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("name");

                    b.HasKey("PermissionId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("LearningLab.Data.Models.AccessControl.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("name");

                    b.HasKey("RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("LearningLab.Data.Models.AccessControl.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("LearningLab.Data.Models.AccessControl.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("LearningLab.Data.Models.Assets.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("asset_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("asset_type");

                    b.PrimitiveCollection<string>("CampaignIds")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("campaign_ids");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<string>("ItemType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("item_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentAssetId")
                        .HasColumnType("int")
                        .HasColumnName("parent_asset_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')");

                    b.HasKey("Id");

                    b.HasIndex("ParentAssetId", "Name")
                        .IsUnique()
                        .HasFilter("[parent_asset_id] IS NOT NULL");

                    b.ToTable("Assets", (string)null);
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.Campaign", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("campaign_id");

                    b.Property<string>("CampaignName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("campaign_name");

                    b.Property<string>("CampaignPictureUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("campaign_picture_url");

                    b.Property<DateTimeOffset>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')");

                    b.Property<Guid>("GameMasterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("game_master_id");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("version");

                    b.HasKey("CampaignId");

                    b.HasIndex("GameMasterId");

                    b.ToTable("Campaigns", (string)null);
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.CampaignMilestone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("campaign_milestone_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("AchievedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("achieved_at");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("description");

                    b.Property<string>("Importance")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("importance");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "Title");

                    b.ToTable("CampaignMilestones", (string)null);
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.CampaignParticipationInvite", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("campaign_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("DateInvited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("date_invited")
                        .HasDefaultValueSql("TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')");

                    b.HasKey("CampaignId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("CampaignParticipationInvite", (string)null);
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.CampaignSettings", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("campaign_id");

                    b.Property<string>("CampaignDescription")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16384)
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("")
                        .HasColumnName("campaign_description");

                    b.Property<int>("MaxNumberOfPlayers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("max_number_of_players");

                    b.Property<string>("PassiveSkillsCheck")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasDefaultValue("Manual")
                        .HasColumnName("passive_skills_check");

                    b.HasKey("CampaignId");

                    b.ToTable("CampaignSettings", (string)null);
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.PlayerCampaignParticipation", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("campaign_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("DateJoined")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("date_joined")
                        .HasDefaultValueSql("TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')");

                    b.Property<string>("Nickname")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("nickname");

                    b.HasKey("CampaignId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("PlayerCampaignParticipation", (string)null);
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.Sessions.CampaignSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("SessionDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("session_date");

                    b.Property<int>("SessionNumber")
                        .HasColumnType("int")
                        .HasColumnName("session_number");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "SessionNumber")
                        .IsUnique();

                    b.ToTable("CampaignSessions", (string)null);
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.Sessions.SessionNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("session_note_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("note_order");

                    b.Property<int>("SessionId")
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("note_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Order")
                        .IsUnique();

                    b.ToTable("SessionNotes", (string)null);
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.Sessions.SessionNoteChoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("session_note_choice_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChoiceText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("choice_text");

                    b.Property<bool>("IsChosen")
                        .HasColumnType("bit")
                        .HasColumnName("is_chosen");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("choice_order");

                    b.Property<int>("SessionNoteId")
                        .HasColumnType("int")
                        .HasColumnName("session_note_id");

                    b.HasKey("Id");

                    b.HasIndex("SessionNoteId", "IsChosen")
                        .IsUnique()
                        .HasFilter("[is_chosen] = 1");

                    b.HasIndex("SessionNoteId", "Order")
                        .IsUnique();

                    b.ToTable("SessionNoteChoices", (string)null);
                });

            modelBuilder.Entity("LearningLab.Data.Models.Character.CharacterSheet", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<string>("Background")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("background");

                    b.Property<string>("CharacterClass")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("character_class");

                    b.PrimitiveCollection<string>("Equipment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("equipment");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_name");

                    b.Property<int?>("Height")
                        .HasColumnType("int")
                        .HasColumnName("height");

                    b.Property<string>("Information")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("information");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_name");

                    b.Property<int>("LogicRating")
                        .HasColumnType("int")
                        .HasColumnName("logic_rating");

                    b.Property<int>("MotoricsRating")
                        .HasColumnType("int")
                        .HasColumnName("motorics_rating");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nationality");

                    b.Property<int>("PhysicalRating")
                        .HasColumnType("int")
                        .HasColumnName("physical_rating");

                    b.Property<string>("PortraitUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("portrait_url");

                    b.Property<int>("PsycheRating")
                        .HasColumnType("int")
                        .HasColumnName("psyche_rating");

                    b.PrimitiveCollection<string>("Traits")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("traits");

                    b.Property<int?>("Weight")
                        .HasColumnType("int")
                        .HasColumnName("weight");

                    b.HasKey("UserId");

                    b.ToTable("CharacterSheets", null, t =>
                        {
                            t.HasCheckConstraint("CK_CharacterSheets_LogicRating", "[logic_rating] BETWEEN 0 AND 15");

                            t.HasCheckConstraint("CK_CharacterSheets_MotoricsRating", "[motorics_rating] BETWEEN 0 AND 15");

                            t.HasCheckConstraint("CK_CharacterSheets_PhysicalRating", "[physical_rating] BETWEEN 0 AND 15");

                            t.HasCheckConstraint("CK_CharacterSheets_PsycheRating", "[psyche_rating] BETWEEN 0 AND 15");
                        });
                });

            modelBuilder.Entity("LearningLab.Data.Models.Notifications.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("notification_id");

                    b.Property<DateTimeOffset>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("date_deleted");

                    b.Property<DateTimeOffset?>("DateRead")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("date_read");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("description");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("notification_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId", "DateDeleted", "DateCreated");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("LearningLab.Data.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_salt");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("LearningLab.Data.Models.AccessControl.RolePermission", b =>
                {
                    b.HasOne("LearningLab.Data.Models.AccessControl.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearningLab.Data.Models.AccessControl.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LearningLab.Data.Models.AccessControl.UserRole", b =>
                {
                    b.HasOne("LearningLab.Data.Models.AccessControl.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearningLab.Data.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearningLab.Data.Models.Assets.Asset", b =>
                {
                    b.HasOne("LearningLab.Data.Models.Assets.Asset", "ParentAsset")
                        .WithMany("Children")
                        .HasForeignKey("ParentAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentAsset");
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.Campaign", b =>
                {
                    b.HasOne("LearningLab.Data.Models.User", "GameMaster")
                        .WithMany("OwnedCampaigns")
                        .HasForeignKey("GameMasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameMaster");
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.CampaignMilestone", b =>
                {
                    b.HasOne("LearningLab.Data.Models.Campaign.Campaign", "Campaign")
                        .WithMany("Milestones")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.CampaignParticipationInvite", b =>
                {
                    b.HasOne("LearningLab.Data.Models.Campaign.Campaign", "Campaign")
                        .WithMany("ParticipationInvites")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearningLab.Data.Models.User", "User")
                        .WithMany("CampaignParticipationInvites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.CampaignSettings", b =>
                {
                    b.HasOne("LearningLab.Data.Models.Campaign.Campaign", "Campaign")
                        .WithOne("Settings")
                        .HasForeignKey("LearningLab.Data.Models.Campaign.CampaignSettings", "CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.PlayerCampaignParticipation", b =>
                {
                    b.HasOne("LearningLab.Data.Models.Campaign.Campaign", "Campaign")
                        .WithMany("PlayerParticipations")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearningLab.Data.Models.User", "User")
                        .WithMany("CampaignParticipations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.Sessions.CampaignSession", b =>
                {
                    b.HasOne("LearningLab.Data.Models.Campaign.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.Sessions.SessionNote", b =>
                {
                    b.HasOne("LearningLab.Data.Models.Campaign.Sessions.CampaignSession", "Session")
                        .WithMany("Notes")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.Sessions.SessionNoteChoice", b =>
                {
                    b.HasOne("LearningLab.Data.Models.Campaign.Sessions.SessionNote", "SessionNote")
                        .WithMany("Choices")
                        .HasForeignKey("SessionNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionNote");
                });

            modelBuilder.Entity("LearningLab.Data.Models.Character.CharacterSheet", b =>
                {
                    b.HasOne("LearningLab.Data.Models.User", "User")
                        .WithOne("CharacterSheet")
                        .HasForeignKey("LearningLab.Data.Models.Character.CharacterSheet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("LearningLab.Data.Models.Character.Action", "Actions", b1 =>
                        {
                            b1.Property<Guid>("CharacterSheetUserId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("ActionType")
                                .IsRequired();

                            b1.Property<string>("Description");

                            b1.Property<string>("Title");

                            b1.HasKey("CharacterSheetUserId", "__synthesizedOrdinal");

                            b1.ToTable("CharacterSheets");

                            b1
                                .ToJson("actions")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("CharacterSheetUserId");
                        });

                    b.Navigation("Actions");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearningLab.Data.Models.Notifications.Notification", b =>
                {
                    b.HasOne("LearningLab.Data.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearningLab.Data.Models.AccessControl.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("LearningLab.Data.Models.AccessControl.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("LearningLab.Data.Models.Assets.Asset", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.Campaign", b =>
                {
                    b.Navigation("Milestones");

                    b.Navigation("ParticipationInvites");

                    b.Navigation("PlayerParticipations");

                    b.Navigation("Settings")
                        .IsRequired();
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.Sessions.CampaignSession", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("LearningLab.Data.Models.Campaign.Sessions.SessionNote", b =>
                {
                    b.Navigation("Choices");
                });

            modelBuilder.Entity("LearningLab.Data.Models.User", b =>
                {
                    b.Navigation("CampaignParticipationInvites");

                    b.Navigation("CampaignParticipations");

                    b.Navigation("CharacterSheet");

                    b.Navigation("Notifications");

                    b.Navigation("OwnedCampaigns");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
